# Generated by Django 5.0.3 on 2024-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0002_remove_userdetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
