# Generated by Django 5.0.3 on 2024-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0003_userdetails_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentholder_id', models.IntegerField(null=True)),
                ('equipment_id', models.IntegerField(null=True)),
                ('username', models.CharField(default='', max_length=75)),
                ('password', models.CharField(default='', max_length=75)),
                ('phone_no', models.IntegerField(null=True)),
                ('village', models.CharField(default='', max_length=75)),
                ('taluka', models.CharField(default='', max_length=75)),
                ('district', models.CharField(default='', max_length=75)),
                ('description', models.TextField(default='', max_length=75)),
                ('old', models.IntegerField(null=True)),
                ('equipmentname', models.CharField(default='', max_length=75)),
                ('rent', models.IntegerField()),
                ('image1', models.ImageField(default='', upload_to='constructapp/images')),
                ('image2', models.ImageField(default='', upload_to='constructapp/images')),
            ],
        ),
    ]
