# Generated by Django 5.0.3 on 2024-03-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0007_alter_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='post',
            field=models.CharField(default='', max_length=75),
        ),
    ]
