# Generated by Django 5.0.3 on 2024-03-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0008_userdetails_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='post',
        ),
    ]
