# Generated by Django 5.0.3 on 2024-03-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0009_remove_userdetails_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='post',
            field=models.CharField(default='', max_length=75),
        ),
    ]
